# Site settings
title: Junction Asia Hackathon
email: junctionasia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Come join us at Junction to learn something new, build an app or start a company.
  Junction brings together people who want to build things for one weekend of hacking.
  Charge your laptops and bring your friends for an amazing event. Let's hack!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://junction.asia" # the base hostname & protocol for your site
twitter_username: junctionasia
github_username:  junctionasia

# Build settings
markdown: kramdown

exclude:
  - node_modules
  - bower_components
  - test
  - bower.json
  - Gruntfile.js
  - package.json
  - README.md
  - Guardfile
  - Gemfile
